### ISSUE TITLE
beginner issue (ϵ not defined)

### ISSUE THREAD

**Issue by ChengweiLou** [pulsipher/InfiniteOpt.jl#202]
I just start with tutorials

I have installed InfiniteOpt, Distributions, Ipopt.

Status `~/.julia/environments/v1.5/Project.toml`
  [c52e3926] Atom v0.12.30
  [31c24e10] Distributions v0.24.18
  [60bf3e95] GLPK v0.14.8
  [20393b10] InfiniteOpt v0.3.2
  [b6b21f68] Ipopt v0.6.5
  [4076af6c] JuMP v0.21.6
  [e5e0dc1b] Juno v0.8.4
  [6405355b] Mosek v1.1.3
  [1ec41992] MosekTools v0.9.4
  [d3f7391f] Plasmo v0.3.3
  [91a5bcdd] Plots v1.11.2

julia> 
ERROR: LoadError: UndefVarError: ϵ not defined
Stacktrace:
 [1] top-level scope at /home/chengwei/github/infinitet1.jl:13
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
in expression starting at /home/chengwei/github/infinitet1.jl:13

Thank you for your help. It seems really useful packages. Hope can use it asap.

**Comment by pulsipher** [comment]
Hi there! 

Is this resolved? If not could you please provide the code you run that triggers this error.

Also, the package versions you are running are pretty old. It also appears you are using Juno which might be part of the problem. Juno is no longer actively developed. As such, I highly recommend that you follow our current installation guide (https://pulsipher.github.io/InfiniteOpt.jl/stable/install/) to install the most current version of Julia directly (currently 1.7) and then install Visual Studio Code and add its "Julia" extension since it is actively being developed and has a number of useful features. Then try to install the most current version of InfiniteOpt.jl (currently v0.5.2) instead of the old v0.3.2 version.

**Comment by ChengweiLou** [comment]
> 

I update my julia and InfiniteOpt.jl , now everything is working well.
