### ISSUE TITLE
Inconsistent result in farmer problem

### ISSUE THREAD

**Issue by sebacea** [pulsipher/InfiniteOpt.jl#269]
**Describe the bug**
I tried to reproduced the [example of the farmer](https://pulsipher.github.io/InfiniteOpt.jl/dev/examples/Stochastic%20Optimization/farmer/#Problem-Setup)  in the documentation

**To Reproduce**
I ran the same code you give in the example

**Expected behavior**
The expected output that is given in the example is:

```julia
Land Allocations: [48.56, 214.77, 236.67]
Expected Profit: $57099.53
```
What I obtained is

```julia
Land Allocations: [221.74, 55.67, 222.58]
Expected Profit: $132751.07
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Package Versions : InfiniteOpt v0.5.5 and JuMP v1.0.0
 - Julia Version: 1.6.2

**Comment by pulsipher** [comment]
Hi @sebacea, thanks for posting an issue. This behavior is actually expected since the random infinite parameters in the farmer problem use random samples; hence, each time the problem is solved different samples will be used which will lead to a different answer. Moreover, since only 10 samples are used the results can vary by quite a bit. In practice, many more samples should be used (e.g., 1,000) and the `Random.seed!` function can be used to seed the random number generator such that the same samples are used each time the script is run. 

I will refine the example to make this more clear.

**Comment by sebacea** [comment]
Ouch. You are right. I forgot that some parameterd were random. Sorry.

Le jeu. 9 juin 2022 à 13:26, Joshua Pulsipher ***@***.***> a
écrit :

**Comment by pulsipher** [comment]
No need to apologize, these type of questions help us to improve the documentation. 

Does this update clear things up?
https://pulsipher.github.io/InfiniteOpt.jl/previews/PR270/examples/Stochastic%20Optimization/farmer/

**Comment by sebacea** [comment]
Absolutely, many thanks!
